# Generated by Django 5.0.3 on 2024-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaviTestServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='nodes',
            field=models.ManyToManyField(default=None, related_name='neighbours', to='NaviTestServer.node'),
        ),
    ]
