# Generated by Django 5.0.3 on 2024-04-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaviTestServer', '0004_floor_alter_node_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='floor',
            name='z',
        ),
        migrations.RemoveField(
            model_name='node',
            name='x',
        ),
        migrations.RemoveField(
            model_name='node',
            name='y',
        ),
        migrations.RemoveField(
            model_name='node',
            name='z',
        ),
        migrations.AddField(
            model_name='node',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NaviTestServer.floor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NaviTestServer.floor')),
                ('points', models.ManyToManyField(to='NaviTestServer.point')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='point',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='NaviTestServer.point'),
            preserve_default=False,
        ),
    ]
