# Generated by Django 5.0.3 on 2024-04-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaviTestServer', '0006_point_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='floor',
        ),
        migrations.AlterField(
            model_name='area',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NaviTestServer.floor', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='node',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NaviTestServer.point', verbose_name='Точка'),
        ),
        migrations.AlterField(
            model_name='point',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NaviTestServer.floor', verbose_name='Этаж'),
        ),
    ]
