# Generated by Django 5.0.3 on 2024-04-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_node_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='neighbours', to='app.node'),
        ),
    ]
