# Generated by Django 5.0.3 on 2024-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_node_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z', models.FloatField()),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('map_image', models.ImageField(blank=True, upload_to='maps/', verbose_name='Карта')),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='neighbours', to='app.node', verbose_name='Соседние узлы'),
        ),
    ]
